### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by eyemiru** [shyamsundar2007/whatsapp-stats#1]
Total conversations: 0
German and English export same issue

**Comment by shyamsundar2007** [comment]
Was this exported from Android? I believe android has a slightly different export file as compared to iOS.

**Comment by eyemiru** [comment]
Yes, on Android

**Comment by shyamsundar2007** [comment]
Currently the code only supports export from iOS. I shall see if I can add Android support soon.

**Comment by shyamsundar2007** [comment]
@eyemiru I have added support for android now. Do let me know if it works.

**Comment by eyemiru** [comment]
Still same error ... Should I send you an exported example chat?

**Comment by shyamsundar2007** [comment]
Yes, please. An exported sample would help.

**Comment by eyemiru** [comment]
Here you go.
[WhatsApp Chat mit User2.txt](https://github.com/shyamsundar2007/whatsapp-stats/files/1310634/WhatsApp.Chat.mit.User2.txt)

**Comment by shyamsundar2007** [comment]
@eyemiru Could you try the latest code now? I've tested it with your file and it seems to work.

**Comment by eyemiru** [comment]
Now it works, thanks  @shyamsundar2007 :)

**Comment by shyamsundar2007** [comment]
Great! Hope it's useful! :)
